<a href="https://colab.research.google.com/github/Gkemhcs/deeplearning-pytorch-notebooks/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("om")

om


In [2]:

import torch

In [3]:
x=torch.Tensor([1,23,34,4])

In [4]:
x.dtype

torch.float32

In [5]:
x**2

tensor([1.0000e+00, 5.2900e+02, 1.1560e+03, 1.6000e+01])

In [6]:
x*torch.tensor([1,2,3,4])

tensor([  1.,  46., 102.,  16.])

In [7]:
x+2

tensor([ 3., 25., 36.,  6.])

In [8]:
x.shape

torch.Size([4])

In [9]:
x.ndim

1

In [10]:
y=torch.Tensor([[1,2,4,4,],[2,4,5,7,],[1,2,4,4,],[2,4,5,5,]])

In [11]:
y[[1,2],3:]

tensor([[7.],
        [4.]])

In [12]:
y.sin_()

tensor([[ 0.8415,  0.9093, -0.7568, -0.7568],
        [ 0.9093, -0.7568, -0.9589,  0.6570],
        [ 0.8415,  0.9093, -0.7568, -0.7568],
        [ 0.9093, -0.7568, -0.9589, -0.9589]])

In [13]:
y

tensor([[ 0.8415,  0.9093, -0.7568, -0.7568],
        [ 0.9093, -0.7568, -0.9589,  0.6570],
        [ 0.8415,  0.9093, -0.7568, -0.7568],
        [ 0.9093, -0.7568, -0.9589, -0.9589]])

In [14]:
y.abs_()

tensor([[0.8415, 0.9093, 0.7568, 0.7568],
        [0.9093, 0.7568, 0.9589, 0.6570],
        [0.8415, 0.9093, 0.7568, 0.7568],
        [0.9093, 0.7568, 0.9589, 0.9589]])

In [15]:
y

tensor([[0.8415, 0.9093, 0.7568, 0.7568],
        [0.9093, 0.7568, 0.9589, 0.6570],
        [0.8415, 0.9093, 0.7568, 0.7568],
        [0.9093, 0.7568, 0.9589, 0.9589]])

In [16]:
y.shape

torch.Size([4, 4])

In [17]:
y.max(dim=0)

torch.return_types.max(
values=tensor([0.9093, 0.9093, 0.9589, 0.9589]),
indices=tensor([1, 0, 1, 3]))

In [18]:
y=y[2:]

In [19]:
y

tensor([[0.8415, 0.9093, 0.7568, 0.7568],
        [0.9093, 0.7568, 0.9589, 0.9589]])

In [20]:
y.max(dim=-1)

torch.return_types.max(
values=tensor([0.9093, 0.9589]),
indices=tensor([1, 2]))

In [21]:
y.shape

torch.Size([2, 4])

In [22]:
torch.cuda.is_available()

True

In [34]:
X=torch.tensor(5.0,requires_grad=True)

In [35]:
X.dim()

0

In [36]:
y=X**2

In [37]:
y

tensor(25., grad_fn=<PowBackward0>)

In [38]:
l=torch.sin(y)

In [39]:
l

tensor(-0.1324, grad_fn=<SinBackward0>)

In [40]:
e=torch.exp(l)+1

In [41]:
e

tensor(1.8760, grad_fn=<AddBackward0>)

In [42]:
el=torch.exp(e)

In [43]:
el

tensor(6.5276, grad_fn=<ExpBackward0>)

In [44]:
el.backward()

In [45]:
l.grad

/tmp/ipython-input-3815194156.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  l.grad


In [46]:
X.grad

tensor(56.6805)

In [48]:
X1=torch.tensor([[25.0,16.0],[9.0,4.0]],requires_grad=True)
Y=X1**2

In [50]:
Y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [52]:
Y

tensor([[625., 256.],
        [ 81.,  16.]], grad_fn=<PowBackward0>)

In [53]:
l=torch.tensor([1,2,3,4])

In [57]:
torch.stack([torch.tensor([1.0]),torch.tensor([2.0])])

tensor([[1.],
        [2.]])

In [67]:
x=torch.tensor([[1,2],[3,4]])
y=torch.tensor([[5,6],[7,8]])

In [68]:
torch.concat(x,y)

TypeError: concat() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (tuple of Tensors tensors, int dim = 0, *, Tensor out = None)
 * (tuple of Tensors tensors, name dim, *, Tensor out = None)


In [69]:
torch.concat([x,y],dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [70]:
torch.concat((x,y),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])